# scene
scene: building
model_id: Placida
is_interactive: true
build_graph: true
load_texture: true
pybullet_load_texture: true
trav_map_resolution: 0.1
trav_map_erosion: 2

# robot
#robot: Fetch
##velocity: 1.0
#wheel_velocity: 1.0
#torso_lift_velocity: 1.0
#arm_velocity: 1.0
robot: Turtlebot
linear_velocity: 0.5
angular_velocity: 1.5707963267948966

# task, observation and action
task: pointgoal # pointgoal|objectgoal|areagoal|reaching
fisheye: false

initial_pos: [4.5, 3.0, 0.]
initial_orn: [0.0, 0.0, 3.14]
#
target_pos: [-2.0, 3.0, 0.0]
target_orn: [0.0, 0.0, 3.14]

is_discrete: false
additional_states_dim: 4
goal_format: polar

# reward
reward_type: geodesic
success_reward: 10.0
slack_reward: 0.0
potential_reward_weight: 3.0
electricity_reward_weight: 0.0
stall_torque_reward_weight: 0.0
collision_reward_weight: -0.5
angle_reward_weight: -0.2

#max_allowed_collisions: 0
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collisions with these robot links
# discount factor
discount_factor: 0.99

# termination condition
dist_tol: 0.3
max_step: 600


# sensor
output: [rgb, depth]
resolution: 128
fov: 90

# display
use_filler: true
display_ui: false
show_diagnostics: false
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]
random:
  random_initial_pose: false
  random_target_pose: false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.1, 0.1]
  random_init_rot_range: [-0.1, 0.1]

speed:
  timestep: 0.001
  frameskip: 10

mode: web_ui #gui|headless
verbose: false
fast_lq_render: true

# visual objects
visual_object_at_initial_target_pos: true
target_visual_object_visible_to_agent: false

# debug
debug: false
